### ISSUE TITLE
Add a rest endpoint for receiving userdata

### ISSUE THREAD

**Issue by partypiet** [adessoAG/project-board#13]
We need an endpoint for receiving information like whether an employee is activated for the project-board or not and if he is, for how long is he activated?

How to receive data about employees dedicated to a specific department?
Which word to use? Employee/User?

I suggest something like:

```
GET   /users
GET   /users/{userId}
GET   /users/{userId}/applications
POST /users/{userId}/applications
GET   /users/{userId}/bookmarks
POST /users/{userId}/bookmarks
```

**Comment by dnl50** [comment]
Done in PR #12

Added endpoint docs in PR comment
